import {afterEach,describe,expect,it,vi} from 'vitest';
import {endpoint,discoverModels,mergeModels,generate,safeAIError} from '../src/ai/client';
import {configKey,loadConfig,persistConfig,scrubSecrets} from '../src/ai/storage';
import {batches,formatSources,retrieve} from '../src/ai/sources';
import {emptyConfig,enabledModels,modelKey,type AIConnection} from '../src/ai/types';
const connection=(protocol:'openai'|'anthropic'='openai'):AIConnection=>({id:protocol,name:'测试连接',protocol,baseUrl:'https://ai.example.test/custom/v1',key:'private-test-sentinel',remember:true,apiType:'chat',models:[{id:'same-model-v1',name:'固定版本',enabled:true}]});
const signal=()=>new AbortController().signal;
function store():Storage {const values=new Map<string,string>();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>{values.set(k,v)},removeItem:k=>{values.delete(k)},clear:()=>values.clear(),key:i=>Array.from(values.keys())[i]||null,get length(){return values.size}};}
const json=(value:unknown)=>new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
function sse(text:string) {const bytes=new TextEncoder().encode(text);return new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close();}}),{headers:{'Content-Type':'text/event-stream'}});}
afterEach(()=>vi.unstubAllGlobals());
describe('browser configuration boundary',()=>{
 it('keeps per-account browser configuration isolated and session keys out of local storage',()=>{const local=store(),session=store();const cfg={...emptyConfig(),connections:[connection(),{...connection('anthropic'),remember:false}],defaultModel:'openai::same-model-v1'};persistConfig('user-a',cfg,local,session);expect(local.getItem(configKey('user-a'))).not.toContain('"id":"anthropic","name":"测试连接","protocol":"anthropic","baseUrl":"https://ai.example.test/custom/v1","key":"private-test-sentinel"');const serialized=JSON.parse(local.getItem(configKey('user-a'))!);expect(serialized.connections[1].key).toBe('');expect(loadConfig('user-a',local,session).connections[1].key).toBe('private-test-sentinel');expect(loadConfig('user-b',local,session).connections).toEqual([]);session.clear();expect(loadConfig('user-a',local,session).connections[1].key).toBe('');});
 it('does not confuse identical model versions across connections',()=>{const cfg={...emptyConfig(),connections:[connection(),connection('anthropic')]};expect(enabledModels(cfg).map(x=>x.id)).toEqual([modelKey('openai','same-model-v1'),modelKey('anthropic','same-model-v1')]);expect(scrubSecrets('echo private-test-sentinel',cfg)).toBe('echo [已隐藏凭据]');});
 it('retains custom root paths and blocks relative URLs and this system as a proxy',()=>{expect(endpoint(connection(),'models','https://workspace.example')).toBe('https://ai.example.test/custom/v1/models');for(const baseUrl of ['/api/ai','https://workspace.example/api','https://user:password@ai.example.test/v1','https://ai.example.test/v1?key=test'])expect(()=>endpoint({...connection(),baseUrl},'models','https://workspace.example')).toThrow();});
});
describe('provider protocols and failure states',()=>{
 it('discovers paginated Anthropic models without testing or losing selected older versions',async()=>{vi.stubGlobal('location',{origin:'https://workspace.example'});const fetcher=vi.fn().mockResolvedValueOnce(json({data:[{id:'m1',display_name:'One'}],has_more:true,last_id:'m1'})).mockResolvedValueOnce(json({data:[{id:'m2'}],has_more:false}));vi.stubGlobal('fetch',fetcher);const found=await discoverModels(connection('anthropic'),signal());expect(found.map(x=>x.id)).toEqual(['m1','m2']);expect(fetcher.mock.calls[1][0]).toContain('after_id=m1');for(const [,options]of fetcher.mock.calls){expect(options.method).toBe('GET');expect(options.body).toBeUndefined();expect(options.credentials).toBe('omit');expect(options.headers['x-api-key']).toBe('private-test-sentinel');}expect(mergeModels([{id:'old-fixed',name:'Old',enabled:true}],found).find(x=>x.id==='old-fixed')).toMatchObject({enabled:true,missing:true});});
 it('sends only explicit content directly to the configured OpenAI endpoint',async()=>{vi.stubGlobal('location',{origin:'https://workspace.example'});const fetcher=vi.fn().mockResolvedValue(json({model:'fixed-response-v2',choices:[{message:{content:'有出处的回答 [S1]'},finish_reason:'stop'}]}));vi.stubGlobal('fetch',fetcher);const result=await generate(connection(),'same-model-v1',[{role:'user',content:'ONLY selected note'}],{signal:signal(),maxTokens:256});expect(result).toMatchObject({model:'fixed-response-v2',requestedModel:'same-model-v1',complete:true});const [url,options]=fetcher.mock.calls[0];expect(url).toBe('https://ai.example.test/custom/v1/chat/completions');expect(options.headers.Authorization).toBe('Bearer private-test-sentinel');expect(options.body).toContain('ONLY selected note');expect(options.body).not.toContain('private-test-sentinel');expect(options.redirect).toBe('error');});
 it.each(['openai-chat','openai-responses','anthropic'])('reads arbitrary UTF-8 stream boundaries for %s',async(kind)=>{vi.stubGlobal('location',{origin:'https://workspace.example'});const c=connection(kind==='anthropic'?'anthropic':'openai');c.apiType=kind==='openai-responses'?'responses':'chat';let events:string;
 if(kind==='anthropic')events='data: {"type":"message_start","message":{"model":"actual-v1"}}\n\ndata: {"type":"content_block_delta","delta":{"type":"text_delta","text":"中文回答 [S1]"}}\n\ndata: {"type":"message_delta","delta":{"stop_reason":"end_turn"}}\n\n';
 else if(kind==='openai-responses')events='data: {"type":"response.output_text.delta","delta":"中文回答 [S1]"}\n\ndata: {"type":"response.completed","response":{"model":"actual-v1"}}\n\n';
 else events='data: {"model":"actual-v1","choices":[{"delta":{"content":"中文回答 [S1]"},"finish_reason":null}]}\n\ndata: {"choices":[{"delta":{},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n';
 vi.stubGlobal('fetch',vi.fn().mockResolvedValue(sse(events)));const values:string[]=[];const result=await generate(c,'version-v1',[{role:'user',content:'来源'}],{signal:signal(),maxTokens:256,onDelta:v=>values.push(v)});expect(result).toMatchObject({text:'中文回答 [S1]',model:'actual-v1',complete:true,truncated:false});expect(values.at(-1)).toBe(result.text);});
 it('marks early stream termination incomplete and output limits truncated',async()=>{vi.stubGlobal('location',{origin:'https://workspace.example'});const fetcher=vi.fn().mockResolvedValueOnce(sse('data: {"choices":[{"delta":{"content":"partial"}}]}\n\n')).mockResolvedValueOnce(json({choices:[{message:{content:'limited'},finish_reason:'length'}]}));vi.stubGlobal('fetch',fetcher);expect((await generate(connection(),'v1',[],{signal:signal(),maxTokens:256,onDelta:()=>{}})).complete).toBe(false);expect((await generate(connection(),'v1',[],{signal:signal(),maxTokens:256})).truncated).toBe(true);});
 it('does not echo upstream error bodies containing credentials',async()=>{vi.stubGlobal('location',{origin:'https://workspace.example'});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('your key private-test-sentinel is invalid',{status:401})));let message='';try{await generate(connection(),'v1',[],{signal:signal(),maxTokens:256});}catch(e){message=safeAIError(e);}expect(message).toContain('HTTP 401');expect(message).not.toContain('private-test-sentinel');});
});
describe('source scope and long reading',()=>{
 const sources=[{id:'n1',title:'实践里的理解',text:'回看知识时，我发现判断已经变化。',kind:'记录',locator:'正文'},{id:'n2',title:'旅行计划',text:'周末去看海。',kind:'记录',locator:'正文'}];
 it('finds Chinese concepts within the supplied space, leaving unrelated notes out',()=>{expect(retrieve(sources,'理解判断的变化').map(x=>x.id)).toEqual(['n1']);expect(retrieve(sources,'不匹配关键词')).toEqual([]);});
 it('keeps original citation numbers through long-file batches',()=>{const long=[sources[0],{...sources[1],text:'材料'.repeat(20000)}];const groups=batches(long);expect(groups.length).toBeGreaterThan(1);expect(formatSources(groups[1],long)).toContain('[S2]');expect(formatSources(groups[1],long)).not.toContain('[S1]');});
});
