import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,FileText,Link2,Paperclip} from 'lucide-react';
import {newItem} from '../lib';
import {useWorkspace} from '../workspace';
import {Body,PageHeading} from '../ui';
import type {Attachment} from '../types';
import {useAI} from './context';
import {AITrigger} from './Provider';
import {readFile,readLink} from './reading';
import {safeAIError} from './client';
export function ReadingView() {
 const ai=useAI();const {ws,space,save,notify,canWrite,open}=useWorkspace();
 const [tab,setTab]=useState('link'),[url,setURL]=useState(''),[paste,setPaste]=useState(''),[thought,setThought]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null),[attachment,setAttachment]=useState<Attachment|null>(null),[saving,setSaving]=useState(false);
 const controller=useRef<AbortController|null>(null);useEffect(()=>()=>controller.current?.abort(),[]);
 const sources=ai.extraSources;const read=async(selected?:File)=>{const c=new AbortController();controller.current=c;const timer=setTimeout(()=>c.abort(),90000);setBusy(true);setStatus(selected?'正在浏览器内提取文件文字…':'正在读取网页正文…');ai.setExtraSources([]);try{const result=selected?await readFile(selected,c.signal,setStatus):await readLink(url,c.signal);if(c.signal.aborted)return;ai.setExtraSources(result);setFile(selected||null);setAttachment(null);if(!selected)setStatus('已取得网页文字，请核对正文后再交给 AI。');ai.open({title:selected?.name||'网页正文',kind:'reading'},'summary');}catch(e){setStatus(safeAIError(e));}finally{clearTimeout(timer);setBusy(false);}};
 const saveSource=async()=>{if(!sources.length||!canWrite||saving)return;setSaving(true);try{let att=attachment;if(file&&!att){const response=await fetch('/api/files',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});const result=await response.json();if(!response.ok)throw new Error(result.error||'文件保存未完成');att=result;setAttachment(att);}const body=sources.map(s=>'## '+s.locator+'\n\n'+s.text).join('\n\n')+(thought.trim()?'\n\n## 我的思考\n\n'+thought:'');if(body.length>500000)throw new Error('材料超过知识正文上限，请拆分后保存。');const item=await save({...newItem('resource',ws.me.owner_id,ws.me.display_name),title:file?.name||sources[0].title,body,source:sources[0].url||url||null,space_id:space||null,atts:att?[att]:[]});notify('来源与自己的思考已保存，未强制调用 AI。');open(item.id);}catch(e){notify((e as Error).message);}finally{setSaving(false);}};
 return <><PageHeading eyebrow="留下材料，也留下自己的发现" title="读一点，想一点" description="先确认读到了什么，再决定需要 AI 帮你提炼什么。" actions={<button className="primary" disabled={!sources.length||!canWrite||saving} onClick={()=>void saveSource()}>保存来源<ArrowRight size={15}/></button>}/><div className="filter-tabs bordered-tabs">{[{id:'link',name:'粘贴链接',icon:Link2},{id:'file',name:'上传文件',icon:Paperclip}].map(t=><button key={t.id} className={tab===t.id?'selected':''} onClick={()=>setTab(t.id)}><t.icon size={15}/>{t.name}</button>)}</div>
 <div className="ai-reading-grid"><section className="ai-reading-input"><h2>{tab==='link'?'从网页留下一个发现':'阅读你带来的文件'}</h2>{tab==='link'?<><label>网页链接<input type="url" value={url} onChange={e=>setURL(e.target.value)} placeholder="https://…" aria-label="阅读网页链接"/></label><button className="primary" disabled={busy||!url.trim()} onClick={()=>void read()}>读取网页<ArrowRight size={15}/></button><details className="ai-paste-source"><summary>网页读不到正文？粘贴正文</summary><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder="粘贴你实际获得的文章正文" aria-label="补充网页正文"/><button className="quiet-button" disabled={!paste.trim()||busy} onClick={()=>{ai.setExtraSources([{id:'paste-'+crypto.randomUUID(),title:'粘贴的阅读材料',text:paste.trim(),kind:'粘贴正文',locator:'用户提供的正文',url:/^https?:\/\//i.test(url)?url:undefined}]);setFile(null);setAttachment(null);setStatus('已补齐正文；来源标注为你粘贴的文字。');ai.open({title:'粘贴的阅读材料',kind:'reading'},'summary');}}>使用这段正文</button></details></>:<label className="ai-file-picker"><FileText size={26}/><strong>选择本地文件</strong><span>TXT / Markdown / PDF / DOCX / HTML / CSV / JSON · 20 MB 以内</span><input type="file" accept=".txt,.md,.markdown,.pdf,.docx,.html,.htm,.csv,.json" disabled={busy} aria-label="选择阅读文件" onChange={e=>{const selected=e.target.files?.[0];if(selected)void read(selected);e.target.value='';}}/></label>}
 <p className="ai-reading-local">文字提取在浏览器进行。只有点击“保存来源”才将材料保存到知识库；AI 只接收你选中的文本。</p>{status&&<p className="ai-status" role="status">{status}</p>}{busy&&<button className="text-button" onClick={()=>controller.current?.abort()}>停止读取</button>}
 {sources.length>0&&<div className="ai-extracted"><div className="ai-section-line"><h3><Check size={15}/>可读材料 · {sources.length} 个片段</h3><AITrigger label="用 AI 接着读" target={{title:'阅读材料',kind:'reading'}} mode="summary"/></div>{sources.map(s=><details key={s.id} open={sources.length===1}><summary>{s.title} · {s.locator} · {s.text.length} 字符</summary><div className="ai-source-preview"><Body text={s.text}/></div></details>)}</div>}
 </section><aside className="ai-reading-thought"><h3>这份材料，让你想到什么？</h3><textarea value={thought} onChange={e=>setThought(e.target.value)} placeholder="一句灵感、一个疑问，或与你已有经验的联系。"/><p>原始材料、AI 提炼和你的理解分别保存。可以只留下自己的发现，也可以将有用的分析收录为补充或经验。</p>{!canWrite&&<p>当前团队为只读，仍可本地阅读与对话。</p>}</aside></div></>;
}
