import {useEffect,useRef,useState} from 'react';
import {Check,Eye,EyeOff,LockKeyhole,Plus,RefreshCw,Trash2} from 'lucide-react';
import {newId,stamp} from '../lib';
import {useAI} from './context';
import {discoverModels,endpoint,generate,mergeModels,safeAIError} from './client';
import {enabledModels,modelKey,type AIConnection,type Protocol} from './types';
const createConnection=(protocol:Protocol):AIConnection=>({id:newId(),name:protocol==='openai'?'我的 OpenAI':'我的 Anthropic',protocol,baseUrl:protocol==='openai'?'https://api.openai.com/v1':'https://api.anthropic.com/v1',key:'',remember:true,apiType:protocol==='openai'?'responses':'chat',models:[]});
export function AISettings() {
 const ai=useAI();const [draft,setDraft]=useState<AIConnection>(()=>ai.config.connections[0]||createConnection('openai'));
 const [showKey,setShowKey]=useState(false),[busy,setBusy]=useState(''),[status,setStatus]=useState(''),[manual,setManual]=useState(''),[manualName,setManualName]=useState(''),[preferred,setPreferred]=useState(ai.config.defaultModel),[maxTokens,setMaxTokens]=useState(ai.config.maxTokens);
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const change=(value:Partial<AIConnection>)=>setDraft(c=>({...c,...value,models:value.models||((value.key!==undefined&&value.key!==c.key||value.baseUrl!==undefined&&value.baseUrl!==c.baseUrl||value.protocol!==undefined&&value.protocol!==c.protocol)?c.models.map(m=>({...m,testedAt:undefined,testError:undefined})):c.models)}));
 const start=()=>{const c=new AbortController();controller.current=c;return c;};
 const detect=async()=>{const c=start();const timer=setTimeout(()=>c.abort(),60000);setBusy('detect');setStatus('正在读取模型目录；不会发送私人笔记。');try{const list=await discoverModels(draft,c.signal);change({models:mergeModels(draft.models,list)});setStatus('发现 '+list.length+' 个模型。勾选常用版本后保存；目录可见不等于调用可用。');}catch(e){setStatus(safeAIError(e));}finally{clearTimeout(timer);setBusy('');}};
 const test=async(id:string)=>{const c=start();const timer=setTimeout(()=>c.abort(),60000);setBusy(id);setStatus('测试会向此 AI 服务发送“只回复 OK”，可能产生少量费用，不发送知识内容。');try{const result=await generate(draft,id,[{role:'user',content:'只回复 OK。'}],{signal:c.signal,maxTokens:512});if(!result.complete||result.truncated)throw new Error('incomplete');change({models:draft.models.map(m=>m.id===id?{...m,testedAt:stamp(),testError:undefined}:m)});setStatus('调用成功：'+id+'。'+(result.model?'响应模型：'+result.model:'服务未确认底层版本。'));}catch(e){const error=safeAIError(e);setStatus(error);if(!c.signal.aborted)change({models:draft.models.map(m=>m.id===id?{...m,testedAt:undefined,testError:error}:m)});}finally{clearTimeout(timer);setBusy('');}};
 const nextConfig={...ai.config,connections:[...ai.config.connections.filter(c=>c.id!==draft.id),draft],maxTokens,defaultModel:preferred};
 const options=enabledModels(nextConfig);
 const save=()=>{try{endpoint(draft,'models');if(!draft.key.trim()){setStatus('填写 API Key 后保存。');return;}const active=options.some(m=>m.id===preferred)?preferred:options[0]?.id||'';ai.updateConfig({...nextConfig,defaultModel:active});setPreferred(active);setStatus('配置已保存在当前浏览器。尚未测试的模型仍可尝试调用。');}catch(e){setStatus(safeAIError(e));}};
 return <div className="ai-settings">
 <div className="ai-local-notice"><LockKeyhole size={19}/><div><strong>API 地址、密钥与模型配置仅保存在你当前的浏览器</strong><p>不会上传到本系统服务器或数据库，也不会随账号同步。浏览器直接调用你设置的 AI 接口；本次选中的内容会发送给该 AI 服务，费用由该服务计收。</p></div></div>
 <div className="ai-settings-layout"><aside className="ai-connections"><small>我的 AI 连接</small>{ai.config.connections.map(c=><button key={c.id} className={c.id===draft.id?'selected':''} disabled={!!busy} onClick={()=>{setDraft(c);setShowKey(false);setStatus('');}}><strong>{c.name}</strong><small>{c.protocol==='openai'?'OpenAI':'Anthropic'} 格式 · {c.models.filter(m=>m.enabled).length} 个常用模型</small></button>)}<button disabled={!!busy} onClick={()=>{setDraft(createConnection('openai'));setShowKey(false);setStatus('新连接尚未保存。');}}><Plus size={14}/>添加 OpenAI 连接</button><button disabled={!!busy} onClick={()=>{setDraft(createConnection('anthropic'));setShowKey(false);setStatus('新连接尚未保存。');}}><Plus size={14}/>添加 Anthropic 连接</button></aside>
 <section><div className="ai-connection-heading"><h2>{draft.name}</h2><span className="tag">浏览器直连</span></div><div className="ai-form-grid">
 <label>连接名称<input value={draft.name} disabled={!!busy} onChange={e=>change({name:e.target.value})}/></label>
 <label>API 格式<select value={draft.protocol} disabled={!!busy} onChange={e=>{const protocol=e.target.value as Protocol;change({protocol,apiType:"chat",baseUrl:["https://api.openai.com/v1","https://api.anthropic.com/v1"].includes(draft.baseUrl)?protocol==="openai"?"https://api.openai.com/v1":"https://api.anthropic.com/v1":draft.baseUrl,models:[]});setStatus('协议已更改，请检查根地址并重新探测模型。');}}><option value="openai">OpenAI 格式</option><option value="anthropic">Anthropic 格式</option></select></label>
 <label className="ai-full">API 根地址<input aria-label="API 根地址" type="url" value={draft.baseUrl} disabled={!!busy} onChange={e=>change({baseUrl:e.target.value})} placeholder="https://api.example.com/v1"/><small>兼容接口请填写服务商提供的根地址。将探测：{draft.baseUrl.replace(/\/$/,'')}/models</small></label>
 <label className="ai-full">API Key<div className="ai-key-field"><input type={showKey?'text':'password'} value={draft.key} disabled={!!busy} autoComplete="off" spellCheck={false} onChange={e=>change({key:e.target.value})} aria-label="AI API Key"/><button className="icon-button" onClick={()=>setShowKey(!showKey)} aria-label={showKey?'隐藏 API Key':'显示 API Key'}>{showKey?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><small>记住浏览器的数据不等于加密；共用设备可选择仅本次会话，并在使用后清除。</small></label>
 </div><section className="ai-model-section"><div className="ai-section-line"><div><h3>选择你会使用的模型</h3><p>可以多选；每次任务使用一个模型，版本以准确 ID 为准。</p></div><button className="quiet-button" disabled={!!busy||!draft.key.trim()} onClick={()=>void detect()}><RefreshCw size={14}/>{busy==='detect'?'探测中…':'探测模型'}</button></div>
 {!draft.models.length&&<p className="ai-placeholder">先探测目录，或手动添加服务商提供的模型 ID。</p>}
 <div className="ai-model-list">{draft.models.map(m=><div key={m.id} className="ai-model-row"><input type="checkbox" checked={m.enabled} disabled={!!busy} aria-label={'启用模型 '+m.id} onChange={e=>change({models:draft.models.map(x=>x.id===m.id?{...x,enabled:e.target.checked}:x)})}/><div><strong>{m.name}</strong><small>{m.id}</small><small>{m.missing?'未在最新目录出现 · ':''}{m.manual?'手动版本 · ':''}{m.capabilities||'能力未确认'}</small></div><span className="ai-model-status">{m.testError?'调用失败':m.testedAt?'测试通过':'待测试'}</span><button className="text-button" disabled={!!busy||!draft.key.trim()} onClick={()=>void test(m.id)}>{busy===m.id?'测试中…':'测试调用'}</button><button className="icon-button" aria-label={'移除模型 '+m.id} disabled={!!busy} onClick={()=>change({models:draft.models.filter(x=>x.id!==m.id)})}><Trash2 size={13}/></button></div>)}</div>
 <div className="ai-manual-model"><input value={manual} disabled={!!busy} aria-label="手动模型 ID" placeholder="准确模型 ID" onChange={e=>setManual(e.target.value)}/><input value={manualName} disabled={!!busy} aria-label="模型显示名称" placeholder="显示名称（可选）" onChange={e=>setManualName(e.target.value)}/><button className="quiet-button" disabled={!!busy||!manual.trim()} onClick={()=>{const id=manual.trim();if(id.length>256||/\s/.test(id)){setStatus('模型 ID 不能含空白或超过 256 字符。');return;}if(!draft.models.some(m=>m.id===id))change({models:[...draft.models,{id,name:manualName.trim()||id,enabled:true,manual:true}]});setManual('');setManualName('');}}><Plus size={14}/>添加版本</button></div>
 </section><details className="ai-advanced"><summary>默认模型与调用偏好</summary><div className="ai-form-grid"><label>默认使用<select value={preferred} onChange={e=>setPreferred(e.target.value)}><option value="">选择默认模型</option>{options.map(x=><option key={x.id} value={x.id}>{x.connection.name} · {x.model.id}</option>)}</select></label>{draft.protocol==='openai'&&<label>OpenAI 调用接口<select value={draft.apiType} onChange={e=>change({apiType:e.target.value as AIConnection['apiType']})}><option value="responses">Responses · 官方 OpenAI</option><option value="chat">Chat Completions · 兼容服务</option></select></label>}<label>密钥保存方式<select value={draft.remember?'local':'session'} onChange={e=>change({remember:e.target.value==='local'})}><option value="local">记住此浏览器</option><option value="session">仅本次浏览器会话</option></select></label><label>最大输出长度<input type="number" min={256} max={8192} value={maxTokens} onChange={e=>setMaxTokens(Math.max(256,Math.min(8192,Number(e.target.value)||2048)))}/></label></div><p>滚动别名可能随服务商更新。固定版本需填写服务商公布的准确 ID；兼容格式不保证支持相同的联网或视觉能力。</p></details>
 {status&&<p className="ai-status" role="status">{status}</p>}
 <div className="ai-settings-footer">{ai.returnToWork&&<button className="quiet-button" onClick={ai.returnToWork}>返回刚才的思考</button>}<small>清理浏览器数据或更换设备后，需要重新配置。</small><div>{busy&&<button className="text-button" onClick={()=>controller.current?.abort()}>停止</button>}<button className="text-button" disabled={!!busy} onClick={()=>{if(confirm('清除当前账号在此浏览器的全部 AI 配置？知识记录会保留。')){ai.clear();setDraft(createConnection('openai'));setPreferred('');setStatus('本地 AI 配置已清除。');}}}>清除本地配置</button>{ai.config.connections.some(c=>c.id===draft.id)&&<button className="text-button" disabled={!!busy} onClick={()=>{if(confirm('删除这个 AI 连接及其本地密钥？')){ai.updateConfig({...ai.config,connections:ai.config.connections.filter(c=>c.id!==draft.id),defaultModel:ai.config.defaultModel.startsWith(draft.id+'::')?'':ai.config.defaultModel});setDraft(createConnection('openai'));}}}>删除连接</button>}<button className="primary" disabled={!!busy} onClick={save}><Check size={14}/>保存到此浏览器</button></div></div>
 </section></div></div>;
}
